
# ${artifactId}'s spring-boot config

#set( $whySetVelocityVariablesLikeThis = 'see: http://stackoverflow.com/questions/31201338/maven-archetype-velocity-error-because-of-a-colon')
#set( $loggingLevelDot = '${LOGGING_LEVEL_:INFO}' )
# TODO use ${artifactId} in LOGGING_FILE default value
#set( $loggingFile = '${LOGGING_FILE:${spring.application.name}}.log' )
#set( $loggingPath = '${LOGGING_PATH:${user.home}/data/${spring.application.name}/logs}' )
#set( $securityUserName = '${SECURITY_USER_NAME:admin}' )
#set( $securityUserPassword = '${SECURITY_USER_PASSWORD:admin_pass}' )
#set( $serverPortWithDefault = '${SERVER_PORT:8080}' )

logging:
  file: $loggingFile
  path: $loggingPath
  level.: $loggingLevelDot

security:
  user:
    name: $securityUserName
    password: $securityUserPassword
    role: ADMIN

server:
  port: $serverPortWithDefault

spring.application.name: ${artifactId}

spring.data.jpa.repositories.enabled: true # Enable JPA repositories.
spring.datasource:
  platform: h2
  maximum-pool-size: 10
  minimum-idle: 5
  name: dataSource
  test-while-idle: true
  time-between-eviction-runs-millis: 1
  validation-query: 'SELECT 1'
  type: 'com.zaxxer.hikari.HikariDataSource'
  driver-class-name: 'org.h2.Driver'
  url: 'jdbc:h2:~/data/${artifactId}/h2' #'jdbc:h2:mem:${artifactId}'
  username: sa

spring.h2.console:
  enabled: true
  web-allow-others: true

spring.jpa:
  database: H2 # Target database to operate on, auto-detected by default. Can be alternatively set using the "databasePlatform" property.
  database-platform: 'org.hibernate.dialect.H2Dialect' # Name of the target database to operate on, auto-detected by default. Can be alternatively set using the "Database" enum.
  generate-ddl: true # Initialize the schema on startup.
  hibernate.ddl-auto: none # DDL mode. This is actually a shortcut for the "hibernate.hbm2ddl.auto" property. Default to "create-drop" when using an embedded database, "none" otherwise.
  hibernate.naming-strategy: 'org.hibernate.cfg.ImprovedNamingStrategy' # Naming strategy fully qualified name.
  #hibernate.naming-strategy: 'spring.jpa.hibernate.naming_strategy=org.hibernate.cfg.EJB3NamingStrategy' # uppercase name
  show-sql: true # Enable logging of SQL statements.

---
spring:
  profiles: development.env

---
spring:
  profiles: it.env

spring.datasource:
  url: 'jdbc:h2:mem:micro-service'

---
spring:
  profiles: staging.env

---
spring:
  profiles: production.env

spring.jpa:
  generate-ddl: false
